"""
O'zbekiston bo'ylab suv namunalari va tadqiqot manbalari ma'lumotlari.
Samarqand davlat universiteti Sun'iy intellekt va raqamli texnologiyalar instituti
ilmiy tadqiqotlari doirasida o'rganilgan suv manbalari.
"""

UZB_WATER_SOURCES = [
    {
        "id": 1,
        "name": "Zarafshon daryosi (Cho'pon ota hududi)",
        "region": "Samarqand viloyati",
        "city": "Samarqand",
        "source_type": "Daryo suvi",
        "lat": 39.6738,
        "lng": 66.9942,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 93.8,
        "ph": 7.42,
        "tds": 245.0,
        "turbidity": 1.2,
        "hardness": 160.0,
        "samples_count": 28,
        "last_tested": "2026-09-24",
        "desc": "Zarafshon daryosining Samarqand hududidagi asosiy oqimi. Fizik-kimyoviy parametrlari SanPiN 0211-06 me'yorlariga to'liq mos."
    },
    {
        "id": 2,
        "name": "Samarqand shahar markaziy vodoprovod tarmog'i",
        "region": "Samarqand viloyati",
        "city": "Samarqand",
        "source_type": "Vodoprovod suvi",
        "lat": 39.6542,
        "lng": 66.9597,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 96.2,
        "ph": 7.15,
        "tds": 210.0,
        "turbidity": 0.6,
        "hardness": 140.0,
        "samples_count": 45,
        "last_tested": "2026-09-26",
        "desc": "SamDU hududi va Samarqand shahri ichimlik suvi ta'minoti. Filtrlash tizimi yuqori darajada ishlaydi."
    },
    {
        "id": 3,
        "name": "Cho'pon ota tabiiy buloq manbai",
        "region": "Samarqand viloyati",
        "city": "Samarqand",
        "source_type": "Buloq suvi",
        "lat": 39.6895,
        "lng": 67.0125,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 98.4,
        "ph": 7.28,
        "tds": 185.0,
        "turbidity": 0.3,
        "hardness": 125.0,
        "samples_count": 16,
        "last_tested": "2026-09-22",
        "desc": "Tog'oldi toza buloq suvi. Minerallashuvi mo'tadil, mikrobiologik jihatdan toza va sog'liq uchun juda foydali."
    },
    {
        "id": 4,
        "name": "Chirchiq daryosi (G'azalkent o'rganish nuqtasi)",
        "region": "Toshkent viloyati",
        "city": "Bo'stonliq",
        "source_type": "Daryo suvi",
        "lat": 41.5604,
        "lng": 69.7708,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 95.1,
        "ph": 7.35,
        "tds": 195.0,
        "turbidity": 0.8,
        "hardness": 130.0,
        "samples_count": 32,
        "last_tested": "2026-09-20",
        "desc": "Tyan-Shan tog'laridan eruvchi qor suvlaridan to'yinuvchi oqim. Kimyoviy ifloslanish kuzatilmagan."
    },
    {
        "id": 5,
        "name": "Chorvoq suv ombori qirg'og'i",
        "region": "Toshkent viloyati",
        "city": "Chorvoq",
        "source_type": "Suv ombori",
        "lat": 41.6312,
        "lng": 70.0275,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 97.6,
        "ph": 7.20,
        "tds": 170.0,
        "turbidity": 0.5,
        "hardness": 115.0,
        "samples_count": 22,
        "last_tested": "2026-09-18",
        "desc": "Toshkent shahri va viloyatining strategik chuchuk suv zaxirasi. Yuqori ekologik tozalik darajasi."
    },
    {
        "id": 6,
        "name": "Bo'zsuv kanali (Toshkent shimoliy tarmog'i)",
        "region": "Toshkent shahri",
        "city": "Toshkent",
        "source_type": "Kanal suvi",
        "lat": 41.3524,
        "lng": 69.2845,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 73.5,
        "ph": 7.85,
        "tds": 480.0,
        "turbidity": 4.6,
        "hardness": 260.0,
        "samples_count": 19,
        "last_tested": "2026-09-23",
        "desc": "Shahar ichidan o'tuvchi kanal. Qaynatish yoki ko'p bosqichli filtrlashdan so'ng iste'mol qilish tavsiya etiladi."
    },
    {
        "id": 7,
        "name": "Amu-Buxoro mashina kanali (Buxoro qismi)",
        "region": "Buxoro viloyati",
        "city": "Buxoro",
        "source_type": "Kanal suvi",
        "lat": 39.7747,
        "lng": 64.4286,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 68.2,
        "ph": 8.05,
        "tds": 620.0,
        "turbidity": 5.8,
        "hardness": 320.0,
        "samples_count": 25,
        "last_tested": "2026-09-19",
        "desc": "Sho'rlanish va qattiqlik darajasi yuqoriroq. Teskari osmos (RO) filtrlash tizimi talab etiladi."
    },
    {
        "id": 8,
        "name": "Qorako'l chuqur artezian qudug'i",
        "region": "Buxoro viloyati",
        "city": "Qorako'l",
        "source_type": "Artezian qudug'i",
        "lat": 39.5028,
        "lng": 63.8562,
        "status": "invalid",
        "status_label": "Yaroqsiz",
        "quality_score": 44.1,
        "ph": 8.42,
        "tds": 1280.0,
        "turbidity": 8.5,
        "hardness": 490.0,
        "samples_count": 14,
        "last_tested": "2026-09-15",
        "desc": "TDS va minerallashuv me'yordan ancha yuqori (1280 mg/L). To'g'ridan-to'g'ri iste'mol qilish salomatlik uchun xavfli."
    },
    {
        "id": 9,
        "name": "Sirdaryo daryosi (Bekobod monitoring stansiyasi)",
        "region": "Toshkent viloyati",
        "city": "Bekobod",
        "source_type": "Daryo suvi",
        "lat": 40.2185,
        "lng": 69.2314,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 71.0,
        "ph": 7.90,
        "tds": 510.0,
        "turbidity": 5.1,
        "hardness": 285.0,
        "samples_count": 18,
        "last_tested": "2026-09-21",
        "desc": "Qishloq xo'jaligi va sanoat ta'siri seziladi. Tozalash inshootlaridan o'tkazilishi shart."
    },
    {
        "id": 10,
        "name": "Norin daryosi (Uchqo'rg'on havzasi)",
        "region": "Namangan viloyati",
        "city": "Uchqo'rg'on",
        "source_type": "Daryo suvi",
        "lat": 41.1165,
        "lng": 72.0792,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 94.6,
        "ph": 7.30,
        "tds": 220.0,
        "turbidity": 1.1,
        "hardness": 145.0,
        "samples_count": 15,
        "last_tested": "2026-09-17",
        "desc": "Farg'ona vodiysining eng toza oqimlaridan biri. Yuqori kislorodli va kam minerallashgan toza suv."
    },
    {
        "id": 11,
        "name": "Chortoq shifobaxsh mineral bulog'i",
        "region": "Namangan viloyati",
        "city": "Chortoq",
        "source_type": "Buloq suvi",
        "lat": 41.0667,
        "lng": 71.8167,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 91.2,
        "ph": 7.45,
        "tds": 390.0,
        "turbidity": 0.4,
        "hardness": 180.0,
        "samples_count": 21,
        "last_tested": "2026-09-16",
        "desc": "Tabiiy mineral buloq suvi. Shifobaxsh mikroelementlarga boy, SanPiN ichimlik me'yorlariga javob beradi."
    },
    {
        "id": 12,
        "name": "Andijonsoy kanali (Andijon shahri)",
        "region": "Andijon viloyati",
        "city": "Andijon",
        "source_type": "Kanal suvi",
        "lat": 40.7821,
        "lng": 72.3442,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 75.3,
        "ph": 7.70,
        "tds": 420.0,
        "turbidity": 4.2,
        "hardness": 230.0,
        "samples_count": 17,
        "last_tested": "2026-09-22",
        "desc": "Shahar magistral kanali. Tozalash va xlorlash talab etiladi."
    },
    {
        "id": 13,
        "name": "Marg'ilonsoy oqimi (Farg'ona)",
        "region": "Farg'ona viloyati",
        "city": "Marg'ilon",
        "source_type": "Daryo suvi",
        "lat": 40.4719,
        "lng": 71.7247,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 76.8,
        "ph": 7.65,
        "tds": 380.0,
        "turbidity": 3.9,
        "hardness": 210.0,
        "samples_count": 20,
        "last_tested": "2026-09-24",
        "desc": "Tog' daryosidan boshlanadi, aholi punktlari oralig'ida loyqalik ortadi. Filtrlash tavsiya etiladi."
    },
    {
        "id": 14,
        "name": "To'polong suv ombori (Sariosiyo)",
        "region": "Surxondaryo viloyati",
        "city": "Sariosiyo",
        "source_type": "Suv ombori",
        "lat": 38.4833,
        "lng": 67.9500,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 96.9,
        "ph": 7.18,
        "tds": 180.0,
        "turbidity": 0.5,
        "hardness": 120.0,
        "samples_count": 13,
        "last_tested": "2026-09-14",
        "desc": "Hisor tog'larining erigan qorlaridan to'yinuvchi yuksak sifatli chuchuk tog' suvi zaxirasi."
    },
    {
        "id": 15,
        "name": "Qashqadaryo daryosi (Qarshi shahri)",
        "region": "Qashqadaryo viloyati",
        "city": "Qarshi",
        "source_type": "Daryo suvi",
        "lat": 38.8606,
        "lng": 65.7891,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 69.4,
        "ph": 8.10,
        "tds": 580.0,
        "turbidity": 6.2,
        "hardness": 310.0,
        "samples_count": 24,
        "last_tested": "2026-09-20",
        "desc": "Yoz-kuz oylarida oqim kamayishi hisobiga minerallashuv ortadi. Mexanik va membrana filtrlash zarur."
    },
    {
        "id": 16,
        "name": "Tuyamo'yin gidrouzeli (Amudaryo quyi oqimi)",
        "region": "Xorazm viloyati",
        "city": "Tuyamo'yin",
        "source_type": "Suv ombori",
        "lat": 41.2189,
        "lng": 61.3972,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 67.5,
        "ph": 8.15,
        "tds": 690.0,
        "turbidity": 6.0,
        "hardness": 340.0,
        "samples_count": 30,
        "last_tested": "2026-09-18",
        "desc": "Xorazm va Qoraqalpog'iston aholisi uchun asosiy suv manbai. Kuchaytirilgan tozalash inshootlari talab qilinadi."
    },
    {
        "id": 17,
        "name": "Nukus shahar suv ta'minoti tarmog'i",
        "region": "Qoraqalpog'iston Respublikasi",
        "city": "Nukus",
        "source_type": "Vodoprovod suvi",
        "lat": 42.4602,
        "lng": 59.6166,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 72.8,
        "ph": 7.95,
        "tds": 540.0,
        "turbidity": 2.8,
        "hardness": 290.0,
        "samples_count": 27,
        "last_tested": "2026-09-23",
        "desc": "Tuyamo'yin-Nukus magistral suvi. Maishiy ehtiyojlar uchun yaroqli, ichish uchun qaynatish/filtrlash tavsiya etiladi."
    },
    {
        "id": 18,
        "name": "Zomin tog' buloqlari (Sangzor havzasi)",
        "region": "Jizzax viloyati",
        "city": "Zomin",
        "source_type": "Buloq suvi",
        "lat": 39.9606,
        "lng": 68.3958,
        "status": "valid",
        "status_label": "Yaroqli (Toza)",
        "quality_score": 97.9,
        "ph": 7.22,
        "tds": 165.0,
        "turbidity": 0.4,
        "hardness": 110.0,
        "samples_count": 18,
        "last_tested": "2026-09-21",
        "desc": "Zomin milliy bog'i tabiiy tog' buloq suvi. Ekologik toza, a'lo darajadagi ichimlik suvi."
    },
    {
        "id": 19,
        "name": "Navoiy shahri Zarafshon o'rta oqimi",
        "region": "Navoiy viloyati",
        "city": "Navoiy",
        "source_type": "Daryo suvi",
        "lat": 40.0844,
        "lng": 65.3792,
        "status": "conditional",
        "status_label": "Shartli yaroqli",
        "quality_score": 74.2,
        "ph": 7.80,
        "tds": 460.0,
        "turbidity": 4.5,
        "hardness": 250.0,
        "samples_count": 16,
        "last_tested": "2026-09-19",
        "desc": "Sanoat shahri yaqinidagi suv monitoring nuqtasi. Muntazam laboratoriya nazoratida."
    },
    {
        "id": 20,
        "name": "Qizilqum artezian qudug'i (Tomdi)",
        "region": "Navoiy viloyati",
        "city": "Tomdibuloq",
        "source_type": "Artezian qudug'i",
        "lat": 41.7333,
        "lng": 64.6167,
        "status": "invalid",
        "status_label": "Yaroqsiz",
        "quality_score": 41.5,
        "ph": 8.60,
        "tds": 1390.0,
        "turbidity": 9.2,
        "hardness": 520.0,
        "samples_count": 11,
        "last_tested": "2026-09-12",
        "desc": "Cho'l mintaqasi chuqur qatlami. Kuchli minerallashgan va sho'r suv. Maxsus chuchuklantirish talab etiladi."
    }
]

def get_water_sources():
    return UZB_WATER_SOURCES
